### ISSUE TITLE
FATA[0000] could not pull monitors

### ISSUE THREAD

**Issue by aioue** [meteor/datadog-sync#3]
### Error message

`FATA[0000] could not pull monitors                       error=json: cannot unmarshal string into Go value of type float64`
### http debug output

```
DEBU[0000] === HTTP ===
Request: &{GET https://app.datadoghq.com/api/v1/monitor?api_key=HIDDEN_API_KEY&application_key=HIDDEN_APP_KEY HTTP/1.1 1 1 map[Content-Type:[application/json]] {0xc8200a05c0} 0 [] false app.datadoghq.com map[] map[] <nil> map[]   <nil> <nil>}
Request body:
Response: &{200 OK 200 HTTP/1.1 1 1 map[Dd-Pool:[dogweb_query]
<snip>
```

**Comment by aioue** [comment]
Wrote own version.

https://github.com/aioue/datadog-edit-monitors-in-place

**Comment by pcarrier** [comment]
@aioue sorry for dropping the ball on that one.

Could you provide `<snip>`?
The exact source of the issue is in there.
You can censor and/or email directly to me (pierre@gcarrier.fr).

**Comment by aioue** [comment]
Sorry @pcarrier, I'm no longer manipulating large globs of DD JSON for work :/
